version: '3'

services:
  #
  # Not working yet inside docker-compose.
  #
  #server:
  #  build: .
  #  depends_on:
  #    - postgres
  #    - localstack
  #  ports:
  #    - "3000:3000"
  #  environment:
  #    DATABASE_URL: postgresql://admin:abc123@postgres:5432/example
  #    AWS_ACCESS_KEY_ID: whatever
  #    AWS_SECRET_ACCESS_KEY: whatever
  #    AWS_REGION: ap-northeast-1
  #    AWS_ENDPOINT: localstack:4566

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "abc123"
      POSTGRES_DB: "example"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  # https://github.com/localstack/localstack/blob/master/docker-compose.yml
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:1.0.0
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      #- "127.0.0.1:53:53"                # DNS config (only required for Pro)
      #- "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
      #- "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    # https://docs.localstack.cloud/localstack/configuration/
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      #- LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
      #- SERVICES=sqs,s3,dynamodb,elasticache,rds # deprecated
      - DEFAULT_REGION=ap-northeast-1

    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
