version: '2'

services:
  server:
    build: .
    depends_on:
      - postgres
    ports:
      - "3002:3000"
    environment:
      DATABASE_URL: "postgresql://admin:abc123@postgres:5432/example"
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "abc123"
      POSTGRES_DB: "example"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

